// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIWPHlWkoplA_4lfTOX9hyQatM2Ul07xI',
    appId: '1:87810950155:web:dbe8b09a014aa8745f330e',
    messagingSenderId: '87810950155',
    projectId: 'jesyon-lekol',
    authDomain: 'jesyon-lekol.firebaseapp.com',
    databaseURL: 'https://jesyon-lekol-default-rtdb.firebaseio.com',
    storageBucket: 'jesyon-lekol.firebasestorage.app',
    measurementId: 'G-PY524MFBPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA8LhmqFkDiak_0Ov_KQOuPuJ5QxX5Oiw',
    appId: '1:87810950155:android:af434ff534de65b65f330e',
    messagingSenderId: '87810950155',
    projectId: 'jesyon-lekol',
    databaseURL: 'https://jesyon-lekol-default-rtdb.firebaseio.com',
    storageBucket: 'jesyon-lekol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZD62hRbbR5E9kBkMMq_m1Px97BfpIxOs',
    appId: '1:87810950155:ios:48a6d945c60452ad5f330e',
    messagingSenderId: '87810950155',
    projectId: 'jesyon-lekol',
    databaseURL: 'https://jesyon-lekol-default-rtdb.firebaseio.com',
    storageBucket: 'jesyon-lekol.firebasestorage.app',
    iosBundleId: 'com.jesyonlekol.jesyonLekol',
  );
}
